### ISSUE TITLE
В чём смысл вынесения size в переменную?

### ISSUE THREAD

**Issue by coursar** [flashxxx2/di#5]
https://github.com/flashxxx2/di/blob/41fde663e40f683511461c47c6eaa36df7569b04/src/main/java/tech/itpark/di/Container.java#L28-L30

**Comment by flashxxx2** [comment]
почему то если я напрямую вставлял for (int i = 0; i < todo.size(); i++) цикл не проходил до конца(выполнялся один раз), думаю это связано с todo.removeAll(generation.keySet());

**Comment by flashxxx2** [comment]
Сейчас убрал использование этой переменной, поэтому закрываю issue
